<!DOCTYPE html>
<html>
<head>
<body>
<h1>Laravel</h1>
<h4>What is Laravel</h4>
<pre> 
	Laravel is an open-source widely used PHP framework. 
	The platform was intended for the development of web application by using MVC architectural pattern.
	Laravel is released under the MIT license.
	Laravel is a free and open-source PHP framework that is used to develop complex web applications. 
	It supports the Model-View-Controller (MVC) design pattern.
</pre> 

<h4>What is the latest version of Laravel?</h4>
<pre>
	Laravel 10
</pre>

<h4>Composer json & lock</h4>
<pre>
	In Laravel, composer.json and composer.lock are two important files used by Composer to manage dependencies.
</pre>	

<h4>Composer.json ?</h4>
<pre>
	composer.json is the main configuration file for Composer
	It lists the dependencies required by the project, including their names and versions.

	When you run composer install or composer update, Composer reads composer.json to determine 
	which dependencies to install or update. If a dependency is not listed in composer.json, it will not be installed.

	Composer is an application-level package manager for PHP.
	It provides a standard format for managing PHP software dependencies and libraries.
	composer requires laravel/passport
	It generates a file(composer.json) in your project directory to 
	keep track of all your packages.
</pre>

<h4>Composer lock ?</h4>
<pre>
	In Laravel, the composer.lock file is an important file used by Composer, a dependency management tool for PHP.

	composer.lock is a file that is generated by Composer when you run composer install or composer update

	It contains a list of all the dependencies that were installed, along with their exact versions. 

	The composer.lock file records the exact version numbers of every package and 
	its dependencies that have been installed for a specific project

	When you run composer install or composer update in a Laravel project, Composer uses the composer.lock 
	file to ensure that the exact same versions of packages and dependencies are installed on every environment. 
	This is important for consistency and compatibility, as different versions of packages may have different requirements or bugs.

	The composer.lock file should be committed to your version control system so that 
	other developers or servers can install the exact same dependencies. This ensures that everyone is working with the same codebase and dependencies, 
	and reduces the risk of unexpected issues caused by different versions of packages.
</pre>	

<h4>Composer json & composer lock? </h4>
<pre> 
	When you run composer install, Composer reads composer.lock to determine which exact versions of dependencies to install.

	If composer.lock is not present, Composer will read composer.json and install the latest compatible versions of the dependencies.

	The composer.json file is a configuration file that defines the dependencies and requirements of your Laravel project, 
	while the composer.lock file is a generated file that contains a complete list of the installed packages and their exact versions, 
	to ensure consistency across environments.
	composer.json is the list of required libraries and versions for your project.
	composer.lock is what is currently installed.
	In Laravel, composer.json and composer.lock are two important files used by Composer to manage dependencies. composer.json specifies 
	the dependencies required by the project and their versions, 
	while composer.lock contains the exact versions of the dependencies that were installed.

	In summary, composer.json specifies the dependencies required by the project, while composer.lock ensures 
	that the exact same versions of dependencies are installed on all machines.
</pre> 

<h4>Composer Install ( Uses composer.lock file) ?</h4>
<pre> 
	When you do composer install it will check for composer.lock file and 
	install all the packages/libraries that are listed in composer.lock file.
	This command won't update anything like composer update.
	Use this command in the Development & Testing stages of your product only. =
	This will update the composer.json & composer.lock files.
</pre> 

<h4>Composer Update ( Refers composer.json file )</h4>
<pre> 
	When you do composer update it will check for the composer.json file and updates all the packages/libraries 
	that are listed in it & once the packages are updated 
	it will rewrite new updates in composer.json & composer.lock file by deleting old package updates.
</pre> 

<h4>What is the templating engine used in Laravel?</h4>
<pre>
	Its powerful templating engine of laravelto write your code modern way with elegant syntax.
	Its own structure such as conditions , loop, display data.
	Store in resources/view directory of laravel
	The templating engine used in Laravel is Blade.
	The blade file has .blade.php extension.
</pre>

<h4>Define environment variables</h4>
<pre>
	The environment variables can be defined in the .env file in the project directory
	A brand new laravel application comes with a .env.example and while installing we copy this file and 
	rename it to .env and all the environment variables will be defined here.

	Some of the examples of environment variables are
	DB_CONNECTION, DB_HOST, DB_PORT,DB_DATABASE, DB_USERNAME,DB_PASSWORD,APP_NAME,APP_KEY,APP_DEBUG,APP_URL
</pre>

<h4>Databases supported by Laravel?</h4>
<pre>
	PostgreSQL
	SQL Server
	SQLite
	MySQL
</pre>
<h4>What artisan</h4>
<pre>
	Artisan is the command-line tool for Laravel to help the developer build the application
	Artisan command can help in creating the files using the make command
</pre>

<h4>Maintenance mode</h4>
<pre>
	Maintenance mode is used to put a maintenance page to customers and under the hood, 
	we can do software updates, bug fixes, etc
	php artisan down
	Can put the application again on live
	php artisan up
</pre>
<h4>Default route files in Laravel</h4>
<pre>
	A route is basically an endpoint specified by a URI (Uniform Resource Identifier).
	It acts as a pointer in Laravel application.

	web.php - For registering web routes.
	api.php - For registering API routes.
	console.php - For registering closure-based console commands.
	channel.php - For registering all your event broadcasting channels that your application supports.
</pre>

<h4>Bundles</h4>
<pre>
	In Laravel, bundles are referred to as packages. These packages are used to increase the functionality of Laravel. 
	A package can have views, configuration, migrations, routes, and tasks.

	Bundles are used to increase the functionality of Laravel. In Laravel, bundles are popularly known as packages. 
	It contains configuration, routes, migrations, views, etc.
</pre>

<h4>Migrations in Laravel?</h4>
<pre>
	In simple, Migrations are used to create database schemas in Laravel. In migration files,
	we store which table to create, update or delete.
	1 up , 2 down
	up() method runs when we run php artisan migrate and 
	down() method runs when we run php artisan migrate:rollback
	
	php artisan migrate:reset : 
	If we want to rollback all migrations
	Rolls back all of the application's migrations, 

	php artisan migrate:refresh : 
	Is a command that rolls back all of the migrations and then executes the migrate command,
	Exffectively re-creating the entire database

	php artisan migrate:fresh :
	Command is used when a fresh or new installation of the database is needed.
	It drops all the existing tables of the database and runs the migrate command
	Drop the all tables first and then run migrations from the start

	php artisan migrate:rollback : 
	Only rolls back the last batch of migrations that were run
</pre>
<h4>Seeders in Laravel</h4>
<pre>
	In Laravel, a seeder is a class used to insert data into the database by running a command
 	It is used to seed test data into a database for testing purposes
	Seeders are stored in the database/seeders directory and can be generated using the make:seeder
</pre>

<h4>Factories</h4>
<pre>
	Factories are a way to put values in fields of a particular model automatically. Like, 
	for testing when we add multiple fake records in the database, 
	we can use factories to generate a class for each model and put data in fields accordingly.
	Every new laravel application comes with database/factories/UserFactory.php
</pre>

<h4>Soft delete in Laravel?</h4>
<pre>
	Soft Delete means when any data row is deleted by any means in the database, 
	we are not deleting the data but adding a timestamp of deletion.
	use SoftDeletes
</pre>

<h4>Models</h4>
<pre>
	With Laravel, each database table can have a model representation using a model file 
	which can be used to interact with that table using Laravel Eloquent ORM.
	We can create a model using this artisan command:

	php artisan make:model Post

<h4>Fillable</h4>
<pre>
	The $fillable attribute is used to define which fields are to be considered when the user will insert or update
	The $fillable attribute is used in Laravel models to specify which fields can be mass-assigned when creating or updating a model instance.
</pre>

<h4>Relationships</h4>
<pre>
	Relationships in Laravel are a way to define relations between different models in the applications. 
	It is the same as relations in relational databases.
	One to One
	One to Many
	Many to Many
	Has One Through
	Has Many Through
	One to One (Polymorphic)
	One to Many (Polymorphic)
	Many to Many (Polymorphic)
</pre>

<h4>Middleware</h4>
<pre>
	Middleware behaves like a bridge and a filtering mechanism between a request and a response.
</pre>

<h4>Eloquent in Laravel</h4>
<pre>
	Eloquent is an object-relational mapper 
	Eloquent is the ORM used to interact with the database using Model classes.
	It gives handy methods on class objects to make a query on the database.
</pre>

<h4>Throttling</h4>
<pre>Throttling is a technique used to limit the number of requests that can be made within a given time frame
	We can create a custom rate limiter called "api" with a limit of 100 requests per minute
	middleware. For example, you can limit requests to a specific route to 60 requests per minute:
	Route::middleware('throttle:60,1')->get('/user', function () { });
</pre>

<h4>Explain logging in Laravel</h4>
<pre>
	Laravel Logging is a way to log information that is happening inside an application. 
	Laravel provides different channels for logging like file and slack. 
	Log messages can be written on to multiple channels at once as well.

We can configure the channel to be used for logging in to our environment file or in the config file at config/logging.php.

 </pre>

<h4>Facades</h4>
<pre>
	A facade in Laravel is a wrapper around a non-static function that turns it into a static function.
	So, in short, Facades are just like a shortcut to a specific class.

</pre>

<h4>What is Localization in Laravel?
</h4>
<pre>
	Localization in Laravel is the process of adapting an application to support multiple languages and cultures. 
	Localization in Laravel involves storing all the strings of different languages in a file, and 
	these files are stored in the resources/lang directory.
	Developers can configure the default language for their application in the 
	config/app.php configuration file, and they can change the active language at runtime using 
	App::setLocale method on the App facad
</pre>

<h4>What are Requests in Laravel?</h4>
<pre>
	Requests in Laravel are a way to interact with incoming HTTP requests along with sessions, 
	cookies, and even files if submitted with the request.
	The class responsible for doing this is Illuminate\Http\Request.
</pre>

<h4>What is a Service Provider?</h4>
<pre>
	
	A Service Provider is a way to bootstrap or register services, events, etc before booting the application.
	Service Providers are the central place of all Laravel application bootstrapping, 
	and they allow developers to share common code across multiple applications.
	Developers can create custom Service Providers by using the php artisan make:provider command, 
	The command will create a Service Provider file in the app/Providers directory
	and they need to register the Service Provider in the config/app.php file to make it available for use in the application.

	A Service Provider is a way to bootstrap or register services, events, etc before booting the application.
</pre>
<h4>Service Container in Laravel</h4>
<pre>
	Service Container in Laravel is a powerful tool for managing class dependencies and performing dependency injection

	The Service Container is a central part of the Laravel framework, and it is used to manage the application's services and dependencies. </pre>


<h4>What is the register and boot method in the Service Provider class?</h4>
<pre>
	The register method in the Service Provider class is used to bind classes or services to the Service Container. 
	It should not be used to access any other functionality or classes from
	 the application as the service you are accessing may not have loaded yet into the container.

	The boot method runs after all the dependencies have been included in the container and now we can access any functionality 
	in the boot method. Like you can create routes, create a view composer, etc in the boot method.

</pre>


<h4>Route</h4>
<pre>
	In Laravel, a route is a definition that maps a URL to a controller method or closure. 
	Routes are used to handle incoming HTTP requests and determine which controller methods should be called to generate the appropriate response
</pre>

<h4>How to define routes in Laravel?
</h4>
<pre>
	Define routes in Laravel, developers can use the routes/web.php file,
 	which is the default route file in Laravel. The web.php file is where developers can define the routes for their application
 	that respond to HTTP requests

<h4>What are named routes?
</h4>
<pre>
	A named route is a route definition with the name assigned to it. We can then use that name to call the route anywhere else in the application.

	Route::get('/hello', 'HomeController@index')->name('index');
	return redirect()->route('index');
</pre>


<h4>What are route groups?
</h4>
<pre>
	Route Groups in laravel is used when we need to group route attributes like middlewares, 
	prefixes, etc. we use route groups. It saves us a headache to put each attribute to each route.
</pre>

<h4>Queues</h4>
<pre>
	While building any application we face a situation where some tasks take time to process and our page gets loading until 
	that task is finished. One task is sending an email when a user registers, we can send the email to the user as a background task, 
	so our main thread is responsive all the time. 

	Queues are a way to run such tasks in the background.

	Queues in Laravel are a mechanism for handling time-consuming tasks, such as sending automated emails or 
	generating detailed reports, without blocking the main application thread

	The queue configuration options are stored in the config/queue.php configuration file
	php artisan queue:work

	1 Create a new job: Generate a new job class using the php artisan make:job command, 
	for example, 
	php artisan make:job SendReminderEmail.
	The generated class will implement the ShouldQueue interface.

	2 Push the job onto the queue   dispatch(new SendReminderEmail);

	3 Run the queue worker php artisan queue:work

</pre>

<h4>What is dependency injection?</h4>
<pre>
	Dependency injection method is used for detaching hard coded class dependencies. 
	It is the process of injecting class dependencies in class through either 
	Laravel service constructir or setter method.</pre>

<h4>Traits</h4>
<pre>
	Laravel traits are a group of functions that you include within another class.
 	A trait is like an abstract class. You cannot instantiate directly, 
 	but its methods can be used in concreate class.
</pre>

<h4>How can we use the custom table in Laravel?
</h4>
<pre>
	Ans. We can use custom table by overriding the protected $table property of Eloquent.
 	protected $table="my_user_table";
</pre>

<h4>Session</h4>
<pre>
	1. forget() method: To delete single item 

	2. flush() method: To delete all session data  

	3. pull() method: To retrieve and then delete session data</pre>
</pre>

<h4>Packages of laravel</h4>
<pre>
	Passport,Socialite,Cashier
</pre>

<h4>What is Middleware and how to create one in Laravel?</h4>
<pre>
	HTTP middleware is a technique for filtering HTTP requests. 
	Laravel includes a middleware that checks whether application user is authenticated or not.

</pre>
<h4>Name aggregates methods of query builder.
</h4>

<pre>
	Aggregates methods of query builder are: 1) max(), 2) min(), 3) sum(), 4) avg(), and 5) count().
</pre>

<h4>What is Event ?</h4>
<pre> 
	Events can be various actions that occur within an application such as email notifications, logging, user sign up, CRUD operations etc.
	
	Event can have multiple listeners and you will divide the code across various files(listeners) instead of writing in one place.

	Events are the ways we hook into the activities of our application, it is just a way to observe an activity, for instance,
	login,a class can be created to monitor the activity of login, when a user logs in, the event class can execute some functions.

	Event classes are typically stored in the app/Events directory
	Registering Events in EventServiceProvider

	Events can be dispatched at any point of your application, the controller, the model, the middleware,

	Simply events are actions that occur within an application. Coming from the world of JavaScript,
	you probably understand events as user actions such as mouse click, mouseover, key press etc.

	Laravel events provide a simple observer implementation, allowing you to subscribe and 
	listen for various events that occur in your application.

	Events are actions that are driven by whatever the programmer wants. 
	If you want to fire an event when somebody loads a page, you can do that. Events can also be a queue and ran via Laravel’s cron job.
</pre> 

<h4>What is Listener?</h4>
<pre> 
	A Listener is a method or small program which will execute once an event is occurred.
	Then Laravel automatically calls the listeners when the event takes place.

	Listeners classes are typically stored in the app/Listeners directory
	Listener class must be mapped to a particular event class.
</pre> 

<h4>Events & listeners</h4>
<pre> 
	Events and listeners is that events are the actions or occurrences that happen in the application,
	while listeners are the classes that handle these events and perform some action in response.
	Events are typically stored in the app/Events directory,
	while their listeners are stored in app/Listeners.
	When an event is fired, all of its registered listeners are executed in the order they were registered

	Events and listeners in Laravel are two separate concepts that work together to implement the observer pattern.
</pre> 

<h4>Generate events</h4>
<pre>
	Now execute php artisan generate:event. This command will generate all the corresponding events and listeners 
	mentioned above in App\Events and App\Listeners directories respectively.

	This command creates Events and Listeners directories under the app folder.
</pre>

<h4>Event and listeners steps</h4>
<pre> 
	1 To register events & Listeners
	2 Generate your  events and Listenersz
	3 Define events and Listeners class
	4 Create table and migration
	5 Dispatch the event

	php artisan make:event EventName
	php artisan make:listener FirstListener --event=EventName
	php artisan event:generate

	App\Providers\EventServiceProvider
</pre> 

<h4>Why Observers Used in Laravel?</h4>
<pre>
	An observer watches for specific things that happen within eloquent such as saving, saved, deleting, deleted 
	(there are more but you should get the point). Observers specifically bound to a model.</pre>

<h4>Migrations</h4>
<pre>
	Migrations in Laravel are a feature that allows developers to define and manage database schema changes in a structured and repeatable way. 
	Migrations work as a version control system for the database schema, 
	allowing developers to programmatically create, update, and destroy database tables.

	A migration class in Laravel contains two methods: up() and down()
	The up() method is used to add new tables, columns, or indexes to the database,
	while the down() method should reverse the operations performed by the up() method

	Within both of these methods, developers may use the Laravel schema builder to define the database schema changes

	To create a new migration in Laravel, developers can use the make:migration Artisan command,
	which generates a new migration file in the database/migrations
	php artisan make:migration create_users_table
	php artisan migrate
</pre>

<h4>Eloquent Models</h4>
<pre>
	object-relational mapping (ORM) system for working with databases.
	Eloquent Models allow developers to interact with database tables as if they were objects,
	making it easier to query and manipulate data.
	Eloquent Models provide methods for examining the internal state of a model and determining how its attributes have changed
	Laravel provides an Artisan command to create an Eloquent Model.
	Eloquent Models are a key part of the Model-View-Controller (MVC) architecture pattern used in Laravel.

	Each database table has a corresponding Model which is used to interact with that table.
	Models allow you to query for data in your tables, as well as insert new records into the table.
</pre>

<h4>Laravel Mail</h4>
<rpe>
	The Mail class is used to send emails directly to a recipient or a list of recipients. 
	It is useful when you need to send a simple email with a custom subject and body.
	You can use the Mailable class to define the email message and the send() method to send the email. 
	The Mail class is more customizable than the Notification class, but it requires more setup and configuration.
</pre>

<h4>Laravel Notification</h4>
<pre>
	The Notification class is used to send notifications to users through different channels,
	such as email, SMS, Slack, and more. 
	It is useful when you need to send a notification to a user or a group of users about an event that occurred in your application.
	You can use the Notifiable trait to define the notification channels for a model and the Notification class to define the notification message.
	The Notification class is less customizable than the Mail class, but it provides a unified way to send notifications through different channels.
</pre>
<h4>Laravel what is different between mail and notification</h4>
<pre>
	The Mail class is used to send simple emails, while the Notification class is used to send notifications through different channels. 
	The choice between the two classes depends on the use case and the requirements of your application.
</pre>

<h4>What is the difference between $fillable and $guarded in Laravel models</h4>
<pre>
	The main difference between $fillable and $guarded is that $fillable is a whitelist approach, 
	meaning that only the attributes listed in $fillable can be mass assigned, while $guarded is a 
	blacklist approach, meaning that any attributes listed in $guarded cannot be mass assigned

	protected $fillable = ['name', 'email', 'password'];

	The User model has the $fillable attribute set to an array of attribute names that can be mass assigned. 
	In this case, only the name, email, and password attributes can be mass assigned.

	protected $guarded = ['id', 'created_at', 'updated_at'];

	In this example, the User model has the $guarded attribute set to an array of attribute names that cannot be mass assigned. 
	In this case, the id, created_at, and updated_at attributes cannot be mass assigned.
</pre>

<h4>Eager loading</h4>
<pre>
	In Laravel, the with method is commonly used when eager loading relationships in Eloquent models.
	Eager loading is a way to retrieve a parent model with its related models in a more efficient way to avoid the N+1 query problem.

	Let's take an example to illustrate eager loading. Suppose you have a Post model and a Comment model, where a post can have many comments. 
	Without eager loading, you might retrieve all posts and then loop through each post to retrieve its comments, resulting in multiple queries.

	$posts = Post::with('comments')->get();
</pre>

<h4>
	How to Download File in Laravel
</h4>
<pre>
	public function downloadFile()
	{
	    $file_path = public_path('path/to/file.pdf');
	    $file_name = 'custom_file_name.pdf';

	    return response()->download($file_path, $file_name);
	}
</pre>

<h4>Which loops are provided by the Blade templating engine?</h4>
<pre>
	Blade templating loops include @endfor, @foreach, @for, @while,  @endforeach, 
	and @endwhile directives.
</pre>

<h4>What are CSRF tokens?</h4>
<pre>
	A Cross Site Request Forgery (CSRF) token is a unique value generated by server-side of an application. 
	It protects web applications against CSRF attacks. These are the attacks that force users to perform unwanted actions.
</pre>

<h4>Explain the use of dd() in Laravel.
</h4>
<pre>
	dd() stands for Dump and Die. It is a helper function is used for dumping a variable’s contents to the browser and stop further script execution. 
	It is used to dump the variable/object and then die the script execution. 
</pre>

<h4>How to Define Fallback Routes in Laravel?</h4>
<pre>
	What is fallback route in laravel?, you may define a route that will be executed when no other route matches the incoming request. 
	So, basically, it's handle 404 error page. you can create your own 404 error using fallback route.

	web.php
	Route::fallback(FallbackController::class);

	controller
	class FallbackController extends Controller
	{   
	    public function __invoke()
	    {
	        return view('fallback');
	    }
	}
</pre>
<h4>Name a few competitors of Laravel?</h4>
<pre>
	Codeigniter
	Symfony
	Yii
	CakePHP
	Zend Framework
	Phalcon
	FuelPHP
</pre>

<h4>Laravel patch and put method</h4>
<pre>
	From what I understand, PATCH is used for updating partial data (a few fields) and PUT is used for updating all the data (all fields).

	Example 1: you have a profile settings page and in the form you want to change only your name 
	but not your twitter account and github account. You'll only update part of the data. For that, you will use a PATCH request.

	Example 2: You have a form with location settings where you have to change all of the fields: City, Country, Zip Code, Address etc. 
	For that, you'll use a PUT request.

	PUT - update a resource (by replacing it with a new version)*
	PATCH - update part of a resource (if available and appropriate)*
</pre>

<h4>Accessors</h4>
<pre>Accessors are used to format or modify attribute values when you retrieve them from a model.
	Accessors are defined using the get{AttributeName}Attribute naming convention,
	like getFullNameAttribute
	when you access the full_name attribute on the model
</pre>

<h4>Mutators</h4>
<pre>
	Mutators are used to format or modify attribute values before they are stored in the database
 	Mutators are defined using the set{AttributeName}Attribute naming convention
 </pre>

<h4>Accessors code</h4>
<pre>
	get{Attribute}Attribute

	public function getFullNameAttribute()
	{
	  return $this->FirstName. " " .$this->LastName;
	}

	{{ $user->full_name }}
</pre>
<h4>Mutator code</h4>
<pre>
	set{Attribute}Attribute

	public function setNameAttribute($value)
	{
	    $this->attributes['name'] = strtolower($value);
	}
</pre>
<h4>Models</h4>
<pre>
	Dates
	protected $dates = ['created_at', 'updated_at'];

	Attribute Casting:
	protected $casts = [
    	'is_admin' => 'boolean',
    	'settings' => 'array',
	];

	Relationships:
	public function posts()
	{
    	return $this->hasMany('App\Models\Post');
	}
</pre>
<h4>Useful Website links</h4>
<pre>
	https://www.interviewbit.com/laravel-interview-questions/
	https://www.guru99.com/laravel-interview-questions.html
	https://www.softwaretestinghelp.com/laravel-interview-questions/
	https://hackr.io/blog/top-laravel-interview-questions-and-answers
	https://www.knowledgehut.com/interview-questions/laravel
	https://www.onlineinterviewquestions.com/laravel-interview-questions/
	https://flexiple.com/laravel/interview-questions/
	https://www.mygreatlearning.com/blog/laravel-interview-questions/
	https://www.bestinterviewquestion.com/laravel-interview-questions
	https://www.adaface.com/blog/laravel-interview-questions/
	https://www.fullstack.cafe/blog/laravel-interview-questions
</pre>
</body>
</html>

